### ISSUE TITLE
Using existing pptx as a reference

### ISSUE THREAD

**Issue by Ashoka74** [leonid20000/odin-slides#1]
Hi Leonid!

Thank you for your work here, your package is working very fast and smoothly.

Correct me if I am wrong but I realized you can only resume from a saved session if it has been already processed beforehand.
After manually modifying the presentation which was produced with odin-slides, the changes I had made were not taken into account in the next iterations.

Would it be possible to use an existing external PPTX as a starting point without deleting slides?

**Comment by leonid20000** [comment]
I'm glad to hear that you're finding the package's speed and smooth performance impressive. It's great that you've identified a situation where resuming from a saved session doesn't account for manual changes to the pptx file. Your observation is accurate, and the reason for this lies in the current approach, where only the processed content is saved and reprocessed in subsequent iterations. While I might revisit this design choice in future updates, for now, the recommended approach is to utilize the tool to generate a solid draft and then proceed to make any necessary manual adjustments.

On another note, it's valuable to discuss scenarios that prompt the need for manual modifications to the pptx file. If these modifications involve adding figures or implementing design changes, the previously mentioned approach is most effective. However, when the goal is to create a presentation based on the content of an existing pptx file, an alternative strategy could involve exporting the manually edited PPTX file into a Word document. In lieu of resuming from a saved session, considering the Word document as a point of reference could prove beneficial.

I will update the readme to clarify this better and perhaps include a video demonstration.

**Comment by leonid20000** [comment]
@Ashoka74 I get your point now. I agree that there are some great benefits to using an existing external PPTX as a starting point. In addition to that, the possibility of recognizing and adopting text modifications made manually to the PPTX file can greatly enhance further revisions carried out by odin-slides. I'm excited to explore this idea further.

I'll set aside some time during the upcoming weekends to make the necessary amendments and see how this approach can improve the workflow. Your input is much appreciated.

**Comment by leonid20000** [comment]
Thank you @Ashoka74 for the suggestion. This feature indeed is useful and elevates the user experience during revisions. Specifically, in situations where the cost/benefit is in favor of the manual fix.

### Latest Updates

#### Version 0.6 (September 27, 2023)

- Added a new feature that allows odin-slides adopt manual modifications done by the user to the pptx text. This includes manually modified text in the title or the content of the slides.
