### ISSUE TITLE
how to set the openai api key ?

### ISSUE THREAD

**Issue by djuillard** [leonid20000/odin-slides#5]
Hello, I created a .env file at the root folder and added ny ODIN_SLIDES_LLM_API_KEY but I still have an error saying that the API Key is not found.
Because I run that program on windows, I also tried to set it up as an environment varibale directly into the windows system, but it's not working neither.

How should I proceed ?

Thanks in advance,

Damien

**Comment by leonid20000** [comment]
If you are on windows try setting the env var in a way that works best for your intended use and the shell that you are using. 
for example in a Powershell session that would be:
`$env:ODIN_SLIDES_LLM_API_KEY = blahblah `

**Comment by djuillard** [comment]
Excellent. It works really fine, awesome projet. Congratulations for your work !!
